# Generated by Django 5.0.6 on 2024-07-08 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeping_time', models.TextField()),
                ('wake_up', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('positivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.positivity')),
            ],
        ),
    ]
