# Generated by Django 5.0.6 on 2024-07-03 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyplanners',
            options={'verbose_name_plural': 'daily planners'},
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=True)),
                ('dailyplanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planners.dailyplanners')),
            ],
        ),
    ]
