# Generated by Django 5.0.6 on 2024-07-04 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planners', '0004_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grateful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grateful', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('dailyplanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planners.dailyplanners')),
            ],
        ),
    ]
