# Generated by Django 5.0.6 on 2024-07-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planners', '0009_exerciseotherinfo_exercisetotalminutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisetotalminutes',
            name='exercise_total_minutes',
            field=models.TimeField(),
        ),
    ]
