# Generated by Django 5.0.6 on 2024-07-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planners', '0010_alter_exercisetotalminutes_exercise_total_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseotherinfo',
            name='exercise_other_info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exercisetotalsteps',
            name='exercise_total_steps',
            field=models.IntegerField(),
        ),
    ]
